[project]
name = "cozi-app-be"
version = "1.0"
dependencies = [
    "fastapi[standard]",
    "psycopg[binary]",
    "sqlalchemy",
    "celery>=5.5.0",
    "alembic",
    "pygtrie~=2.5.0",
    "pyjwt",
    "pycryptodome",
    "python-multipart",
    "bcrypt",
    "opentelemetry-distro==0.58b0",
    "opentelemetry-exporter-otlp",
    "opentelemetry-instrumentation-fastapi",
    "opentelemetry-instrumentation-logging",
    "prometheus-fastapi-instrumentator",
    "opentelemetry-sdk",
    "opentelemetry-exporter-prometheus",
]

[project.optional-dependencies]
local = [
    "black",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "testcontainers[postgres]",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli = true
addopts = "--import-mode=importlib -p core.services.load_test_env"