apiVersion: 1

prune: true

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: false

- name: Tempo
  type: tempo
  access: proxy
  url: http://tempo:3200/
  basicAuth: false
  editable: false
  jsonData:
    httpMethod: GET
    tracesToLogsV2:
      datasourceUid: Loki
      filterByTraceID: true
    tracesToMetrics:
      datasourceUid: Prometheus
      tags:
        - key: service.name
          value: service_name
        - key: http.route
          value: http_route
      queries:
        - name: "Request Rate"
          query: 'rate(traces_spanmetrics_calls_total{$$__tags}[5m])'
        - name: "Error Rate"
          query: 'rate(traces_spanmetrics_calls_total{$$__tags,status_code="STATUS_CODE_ERROR"}[5m])'
        - name: "P95 Latency"
          query: 'histogram_quantile(0.95,rate(traces_spanmetrics_duration_milliseconds_bucket{$$__tags}[5m]))'
    serviceMap:
      datasourceUid: Prometheus

- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  jsonData:
    maxLines: 1000
