"""modified_booking_table

Revision ID: 98464cf761eb
Revises: 05f53557b9c0
Create Date: 2026-05-25 10:12:48.717356+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core


# revision identifiers, used by Alembic.
revision: str = "98464cf761eb"
down_revision: Union[str, Sequence[str], None] = "05f53557b9c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bookings",
        "check_in",
        existing_type=sa.DATE(),
        type_=core.tools.sqlalchemy.utc_date_time.UTCDateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "check_out",
        existing_type=sa.DATE(),
        type_=core.tools.sqlalchemy.utc_date_time.UTCDateTime(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bookings",
        "check_out",
        existing_type=core.tools.sqlalchemy.utc_date_time.UTCDateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "check_in",
        existing_type=core.tools.sqlalchemy.utc_date_time.UTCDateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
