"""modified_tables_for_booking_api

Revision ID: aa9cd41e555b
Revises: b4a6fe2908f2
Create Date: 2026-05-31 16:13:35.125013+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9cd41e555b'
down_revision: Union[str, Sequence[str], None] = 'b4a6fe2908f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('nights', sa.Integer(), nullable=True))
    op.add_column('resorts', sa.Column('base_price_per_day_use', sa.Numeric(precision=12, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resorts', 'base_price_per_day_use')
    op.drop_column('bookings', 'nights')
    # ### end Alembic commands ###
