"""modified_resort_review_table

Revision ID: 3849ee14cd9c
Revises: 35d510aab334
Create Date: 2026-05-23 15:20:23.377132+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3849ee14cd9c'
down_revision: Union[str, Sequence[str], None] = '35d510aab334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resort_reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resort_reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
