"""purpose_manager_password_reset_request

Revision ID: e6abe787a373
Revises: 52d0e5a09317
Create Date: 2026-10-10 15:02:25.890344+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6abe787a373'
down_revision: Union[str, Sequence[str], None] = '52d0e5a09317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager_password_reset_requests', sa.Column('purpose', sa.String(length=24), server_default='RESET', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager_password_reset_requests', 'purpose')
    # ### end Alembic commands ###
