"""admin_manager_verification

Revision ID: e5ca09ef21ec
Revises: aa9cd41e555b
Create Date: 2026-10-02 09:55:34.127116+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import core

# revision identifiers, used by Alembic.
revision: str = "e5ca09ef21ec"
down_revision: Union[str, Sequence[str], None] = "aa9cd41e555b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manager_verifications",
        sa.Column("manager_id", sa.String(length=256), nullable=False),
        sa.Column("latest_email_sent_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("verified_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("created_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("updated_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("deleted_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["admins.id"],
        ),
        sa.PrimaryKeyConstraint("manager_id"),
    )
    op.add_column("admins", sa.Column("first_name", sa.String(length=50), nullable=True))
    op.add_column("admins", sa.Column("last_name", sa.String(length=50), nullable=True))
    op.add_column("admins", sa.Column("phone_number", sa.String(length=50), nullable=True))
    op.alter_column("admins", "organization_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("admins", "resort_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("admins", "updated_at")
    op.drop_column("admins", "created_at")
    op.drop_column("admins", "deleted_at")
    op.drop_column("masters", "updated_at")
    op.drop_column("masters", "created_at")
    op.drop_column("masters", "deleted_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("masters", sa.Column("deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column("masters", sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column("masters", sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column("admins", sa.Column("deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column("admins", sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column("admins", sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column("admins", "resort_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("admins", "organization_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("admins", "phone_number")
    op.drop_column("admins", "last_name")
    op.drop_column("admins", "first_name")
    op.drop_table("manager_verifications")
    # ### end Alembic commands ###
