"""init

Revision ID: cf6eaea53057
Revises:
Create Date: 2026-01-03 14:58:37.096274+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import core

# revision identifiers, used by Alembic.
revision: str = "cf6eaea53057"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("email_address", sa.String(length=256), nullable=True),
        sa.Column("user_type", sa.String(length=256), nullable=False),
        sa.Column("hashed_password", postgresql.BYTEA(), nullable=True),
        sa.Column("created_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("updated_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("deleted_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "guests",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("phone_number", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guests")
    op.drop_table("users")
    # ### end Alembic commands ###
