"""manager_password_reset_request

Revision ID: 8ff5027010d1
Revises: 1621a7baa188
Create Date: 2026-10-02 20:27:11.376511+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core


# revision identifiers, used by Alembic.
revision: str = "8ff5027010d1"
down_revision: Union[str, Sequence[str], None] = "1621a7baa188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manager_password_reset_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("manager_id", sa.String(length=256), nullable=False),
        sa.Column("expires_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("request_consumed_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("created_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("updated_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("deleted_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["admins.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manager_password_reset_requests_manager_id"),
        "manager_password_reset_requests",
        ["manager_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_manager_password_reset_requests_manager_id"), table_name="manager_password_reset_requests")
    op.drop_table("manager_password_reset_requests")
    # ### end Alembic commands ###
