"""unique_constraint_on_resort_name

Revision ID: 52d0e5a09317
Revises: d5419cc2a014
Create Date: 2026-10-08 11:11:35.454370+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d0e5a09317'
down_revision: Union[str, Sequence[str], None] = 'd5419cc2a014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_resorts_organization_id_name', 'resorts', ['organization_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_resorts_organization_id_name', 'resorts', type_='unique')
    # ### end Alembic commands ###
