"""admin_managerpasswordverification_master_resort_modification

Revision ID: d5419cc2a014
Revises: 8ff5027010d1
Create Date: 2026-10-03 15:15:09.223754+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5419cc2a014"
down_revision: Union[str, Sequence[str], None] = "8ff5027010d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "admins", ["resort_id"])
    op.create_foreign_key(None, "admins", "resorts", ["resort_id"], ["id"])
    op.drop_column("admins", "organization_id")
    op.drop_constraint(
        op.f("manager_password_reset_requests_manager_id_fkey"), "manager_password_reset_requests", type_="foreignkey"
    )
    op.create_foreign_key(None, "manager_password_reset_requests", "users", ["manager_id"], ["id"])
    op.drop_constraint(op.f("manager_verifications_manager_id_fkey"), "manager_verifications", type_="foreignkey")
    op.create_foreign_key(None, "manager_verifications", "users", ["manager_id"], ["id"])
    op.add_column("masters", sa.Column("first_name", sa.String(length=50), nullable=True))
    op.add_column("masters", sa.Column("last_name", sa.String(length=50), nullable=True))
    op.add_column("masters", sa.Column("phone_number", sa.String(length=50), nullable=True))
    op.add_column("masters", sa.Column("organization_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "masters", ["organization_id"])
    op.drop_constraint(op.f("masters_project_id_fkey"), "masters", type_="foreignkey")
    op.create_foreign_key(None, "masters", "organizations", ["organization_id"], ["id"])
    op.drop_column("masters", "project_id")
    op.create_foreign_key(None, "resorts", "organizations", ["organization_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resorts", type_="foreignkey")
    op.add_column("masters", sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "masters", type_="foreignkey")
    op.create_foreign_key(op.f("masters_project_id_fkey"), "masters", "organizations", ["project_id"], ["id"])
    op.drop_constraint(None, "masters", type_="unique")
    op.drop_column("masters", "organization_id")
    op.drop_column("masters", "phone_number")
    op.drop_column("masters", "last_name")
    op.drop_column("masters", "first_name")
    op.drop_constraint(None, "manager_verifications", type_="foreignkey")
    op.create_foreign_key(
        op.f("manager_verifications_manager_id_fkey"), "manager_verifications", "admins", ["manager_id"], ["id"]
    )
    op.drop_constraint(None, "manager_password_reset_requests", type_="foreignkey")
    op.create_foreign_key(
        op.f("manager_password_reset_requests_manager_id_fkey"),
        "manager_password_reset_requests",
        "admins",
        ["manager_id"],
        ["id"],
    )
    op.add_column("admins", sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "admins", type_="foreignkey")
    op.drop_constraint(None, "admins", type_="unique")
    # ### end Alembic commands ###
