"""booking_and_payment_table

Revision ID: 05f53557b9c0
Revises: 3849ee14cd9c
Create Date: 2026-05-25 09:10:36.545664+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core


# revision identifiers, used by Alembic.
revision: str = "05f53557b9c0"
down_revision: Union[str, Sequence[str], None] = "3849ee14cd9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guest_id", sa.String(length=256), nullable=False),
        sa.Column("resort_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("num_guests", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=24), nullable=False),
        sa.Column("special_request", sa.Text(), nullable=True),
        sa.Column("cancelled_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("created_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("updated_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("deleted_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resort_id"],
            ["resorts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("booking_table_index", "bookings", ["status", "check_in", "check_out"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column("payment_intent_amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=24), nullable=False),
        sa.Column("payment_method", sa.String(length=24), nullable=False),
        sa.Column("payment_intent_id", sa.String(length=256), nullable=False),
        sa.Column("client_key", sa.String(length=256), nullable=False),
        sa.Column("paymongo_status", sa.String(length=64), nullable=False),
        sa.Column("payment_id", sa.String(length=256), nullable=True),
        sa.Column("net_amount", sa.Float(), nullable=True),
        sa.Column("fee", sa.Float(), nullable=True),
        sa.Column("balance_transaction_id", sa.String(length=256), nullable=True),
        sa.Column("source_id", sa.String(length=256), nullable=True),
        sa.Column("event_id", sa.String(length=256), nullable=True),
        sa.Column("payment_response", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("updated_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("deleted_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_intent_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_index("booking_table_index", table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###
