"""guest_verification table

Revision ID: 1768b4e0de4a
Revises: cf6eaea53057
Create Date: 2026-03-20 11:29:25.262435+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core


# revision identifiers, used by Alembic.
revision: str = "1768b4e0de4a"
down_revision: Union[str, Sequence[str], None] = "cf6eaea53057"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest_verifications",
        sa.Column("guest_id", sa.String(length=256), nullable=False),
        sa.Column("latest_email_sent_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("verified_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("created_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("updated_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("deleted_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guests.id"],
        ),
        sa.PrimaryKeyConstraint("guest_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guest_verifications")
    # ### end Alembic commands ###
