"""modified_resorts_related_table

Revision ID: 35d510aab334
Revises: 2eafab6afe9a
Create Date: 2026-05-23 14:05:14.878384+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35d510aab334'
down_revision: Union[str, Sequence[str], None] = '2eafab6afe9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resort_rooms_resort_id'), table_name='resort_rooms')
    op.drop_table('resort_rooms')
    op.add_column('resorts', sa.Column('num_bedrooms', sa.Integer(), nullable=False))
    op.add_column('resorts', sa.Column('num_bathrooms', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resorts', 'num_bathrooms')
    op.drop_column('resorts', 'num_bedrooms')
    op.create_table('resort_rooms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resort_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unavailable_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resort_id'], ['resorts.id'], name=op.f('resort_rooms_resort_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resort_rooms_pkey'))
    )
    op.create_index(op.f('ix_resort_rooms_resort_id'), 'resort_rooms', ['resort_id'], unique=False)
    # ### end Alembic commands ###
