"""guest_reset_password_request

Revision ID: 1621a7baa188
Revises: e5ca09ef21ec
Create Date: 2026-10-02 14:48:44.910179+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core


# revision identifiers, used by Alembic.
revision: str = "1621a7baa188"
down_revision: Union[str, Sequence[str], None] = "e5ca09ef21ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest_password_reset_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guest_id", sa.String(length=256), nullable=False),
        sa.Column("expires_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("request_consumed_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("created_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=False),
        sa.Column("updated_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.Column("deleted_at", core.tools.sqlalchemy.utc_date_time.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guest_password_reset_requests")
    # ### end Alembic commands ###
