services:
  app:
    build:
      context: ../../
      dockerfile: docker/cozi-app-be-develop/Dockerfile
      target: fastapi
    env_file:
      - ../../env/develop.env
#    ports:
#      - "8000:8000" TRAEFIK WILL NOW HANDLE THIS SINCE IT IS THE MAIN ENTRY POINT TO ALL THE SERVICES
    volumes:
      - ../../src:/app/src
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`cozi-api.localhost`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
    networks:
      - traefik-public
      - observability
      - rabbitmq_network

  celery_worker:
    build:
      context: ../../
      dockerfile: docker/cozi-app-be-develop/Dockerfile
      target: celery_worker
    env_file:
      - ../../env/develop.env
    volumes:
      - ../../src:/app/src
    restart: unless-stopped
    networks:
      - rabbitmq_network
      - observability

networks:
  traefik-public:
    external: true
  observability:
    external: true
  rabbitmq_network:
    external: true
