services:
  app:
    build:
      context: ../../
      dockerfile: docker/cozi-app-be-develop/Dockerfile
      target: fastapi
    env_file:
      - ../../env/develop.env
    ports:
      - "8000:8000"
    volumes:
      - ../../src:/app/src
    networks:
      - observability
      - rabbitmq_network

  celery_worker:
    build:
      context: ../../
      dockerfile: docker/cozi-app-be-develop/Dockerfile
      target: celery_worker
    env_file:
      - ../../env/develop.env
    volumes:
      - ../../src:/app/src
    restart: unless-stopped
    networks:
      - rabbitmq_network
      - observability

networks:
  observability:
    external: true
  rabbitmq_network:
    external: true
