services:
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../../docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
    networks:
      - traefik-public

networks:
  traefik-public:
    name: traefik-public
    driver: bridge
